#! /bin/bash

dir=$1

if [ -z "${dir}" ]; then
    echo "Missing directory parameter. Usage: catcue <DIRECTORY>"
    exit 1
fi

if [ ! -d "${dir}" ]; then
    exit 1
fi

if [[ `ls "${dir}/" | wc -l | bc` -eq 0 ]]; then
    exit 1
fi

# GROUP_NAME
export GRP="GROUP_NAME"

if [[ `ls "${dir}/" | grep "\[${GRP}\]" --color=never | wc -l | bc` -eq 0 ]]; then
    cue_file=`ls ${dir}/* | grep -E '^0{2,3}' --color=never | grep '\.cue' --color=never`
    if [ ! ${cue_file} ]; then
        cue_file=`ls ${dir}/* | grep '\.cue' --color=never | head -n 1`
    fi
    if [[ -f ${cue_file} ]]; then
        check_cue $dir $cue_file
    fi
fi

exit 0
