#! /bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
LIGHT_GREY='\033[0;37m'
DARK_GREY='\033[1;30m'
NC='\033[0m' # No Color

dir=$1
m3u_file=$2

if [ -z "${dir}" ]; then
    echo "Missing directory parameter. Usage: check_m3u <DIRECTORY> <M3U_FILE>"
    exit 1
fi

if [ ! -d "${dir}" ]; then
    exit 1
fi

if [[ `ls "${dir}/" | wc -l | bc` -eq 0 ]]; then
    exit 1
fi

if [ -z "${m3u_file}" ]; then
    echo "Missing m3u_file parameter. Usage: check_m3u <DIRECTORY> <M3U_FILE>"
    exit 1
fi

if [ ! -f "${m3u_file}" ]; then
    exit 1
fi

ext='\.(wav|aif|aiff|flac|mp3|m4a)'
currenttime=$(date "+%Y.%m.%d-%H.%M.%S")
dir_name=${dir//[^[:alnum:]]/}
file1="/tmp/sc1-filecheck-${dir_name}-${currenttime}"
file2="/tmp/sc2-filecheck-${dir_name}-${currenttime}"
ls -1a ${dir} | grep -E ${ext} --color=never > ${file1}
cat ${m3u_file} | grep -E ${ext} --color=never > ${file2}

if [ `diff -i -B --strip-trailing-cr ${file1} ${file2} | wc -l | bc` == 0 ]; then
    echo -e "${DARK_GREY}${d} ${NC}${LIGHT_GREY}${dir}${NC} ${GREEN}✓${NC}"
else
    echo -e "${DARK_GREY}${d} ${NC}${LIGHT_GREY}${dir}${NC} ${RED}✖${NC}"
    echo -e "${LIGHT_GREY}$(diff ${file1} ${file2})${NC}"
fi
if [ -f ${file1} ]; then
    rm -f ${file1}
fi
if [ -f ${file2} ]; then
    rm -f ${file2}
fi

exit 0
