#! /bin/bash

dir=$1

if [ -z "${dir}" ]; then
    echo "Missing directory parameter. Usage: setdate <DIRECTORY>"
    exit 1
fi

if [ ! -d "${dir}" ]; then
    exit 1
fi

if [[ `ls "${dir}/" | wc -l | bc` -eq 0 ]]; then
    exit 1
fi

for i in $(ls -Ap ${dir} | grep -v -e "^\[${GRP}\]" | sort -r); do
    touch ${dir}/${i}
    setfile ${dir}/${i}
done

touch ${dir}
setfile ${dir}

exit 0
