#! /bin/bash

file=$1

if [ -z "${file}" ]; then
    echo "Missing file parameter. Usage: setfile <FILE_OR_DIRECTORY>"
    exit 1
fi

date=`/usr/bin/GetFileInfo -m ${file}`
/usr/bin/SetFile -d "${date}" ${file}

exit 0
