#! /bin/bash

file=$1

if [ -z "${file}" ]; then
    echo "Missing file parameter. Usage: setfile <FILE_OR_DIRECTORY>"
    exit 1
fi

date=`GetFileInfo -m ${file}`
SetFile -d "${date}" ${file}

exit 0
